global:
  scrape_interval: 5s
  external_labels:
    stack: "apisix"
scrape_configs:

  - job_name: "wakapi"
    scrape_interval: 1m
    metrics_path: "/api/metrics"
    bearer_token: "OWVmYzVlY2YtNDc4MC00MWNiLWExNjAtNDg2MTk2ODc1NmFkCg=="
    static_configs:
      - targets: ["test"]
    scheme: https
    tls_config:
      insecure_skip_verify: true

